# Sử dụng hình ảnh OpenJDK làm cơ sở
FROM openjdk:11-jdk-slim

# Đặt biến môi trường để xác định tên tệp JAR
ARG JAR_FILE=target/*.jar

# Sao chép tệp JAR vào container
COPY ${JAR_FILE} app.jar
EXPOSE 8080
# Đặt entrypoint để chạy ứng dụng
ENTRYPOINT ["java","-jar","/app.jar"]
